name: Release branch manually

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        platform:
          - linux/arm64

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}

      - name: Build and push router Docker image
        uses: docker/build-push-action@v4
        with:
          build-args: |
            BINARY=router
          platforms: ${{ matrix.platform }}
          push: true
          tags: juspaydotin/orca:${{ github.sha }}

      - name: Build and push consumer Docker image
        uses: docker/build-push-action@v4
        with:
          build-args: |
            BINARY=scheduler
            SCHEDULER_FLOW=Consumer
          platforms: ${{ matrix.platform }}
          push: true
          tags: juspaydotin/orca-consumer:${{ github.sha }}

      - name: Build and push producer Docker image
        uses: docker/build-push-action@v4
        with:
          build-args: |
            BINARY=scheduler
            SCHEDULER_FLOW=Producer
          platforms: ${{ matrix.platform }}
          push: true
          tags: juspaydotin/orca-producer:${{ github.sha }}

      - name: Build and push drainer Docker image
        uses: docker/build-push-action@v4
        with:
          build-args: |
            BINARY=drainer
          platforms: ${{ matrix.platform }}
          push: true
          tags: juspaydotin/orca:drainer-${{ github.sha }}
