name: Postman Api test 

on:
  pull_request:
    branches:
      - main
  schedule:
      - cron: "15 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  api_tests:
    name: Run integration tests on backend APIs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.1.0
      
      - name: Install Newman
        run: npm install -g newman
      
      - name: Install portman
        run: npm install -g @apideck/portman
      
      - name: Generate postman collection
        run: portman --cliOptionsFile postman/portman-cli.json

      - name: Run Newman
        run: newman run postman/collection.postman.json --env-var apiKey=${{ secrets.INTEG_ADMIN_API_KEY }} baseUrl=${{ secrets.INTEG_BASE_URL }}